#!/bin/bash

to_install=''

if ! dpkg -s amulet &> /dev/null; then
    sudo add-apt-repository -y ppa:juju/stable
    sudo apt-get update
    to_install="$to_install amulet"
fi

if ! dpkg -s python3-yaml &> /dev/null; then
    to_install="$to_install python3-yaml"
fi

if [[ -n "$to_install" ]]; then
    echo Installing $to_install...
    sudo apt-get install $to_install
fi
